language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
    directories:
    - $HOME/.m2

script: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - mura2393@nate.com