spring:
  profiles:
    active: local # basic

---
spring:
  profiles: local
server:
  port: 8080

---
spring:
  profiles: set1
server:
  port: 8081

---
spring:
  profiles: set2

server:
  port: 8082